name: pylsl
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  pull_request:
  schedule:
  - cron: '0 8 * * 1'

jobs:
  sha256:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    env:
      SHA256_PYLSL: dd9222ee3894c43535b40aee542a2c8cb6062a467d4b103bd3c3a713d7c7690c
    steps:
      - name: Checkout pylsl repository
        uses: actions/checkout@v3
        with:
          repository: labstreaminglayer/pylsl
      - name: Compare checksum
        run: echo "$SHA256_PYLSL pylsl/pylsl.py" | sha256sum -c
      - name: Create GitHub issue
        if: failure()
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Test issue
          body: |
            ### pyLSL is out of sync with BSL
            [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            Workflow name - `${{ github.workflow }}`
            Job -           `${{ github.job }}`
            status -        `${{ job.status }}`

            Please visit https://github.com/labstreaminglayer/pylsl and review the changes.
          assignees: mscheltienne
